{% set version = "3.0.2" %}
{% set checksum = "e7a8bae66a2ae713856a53e2beeedf789020e4f2e1edd0a2756673aa0f8041f2" %}

package:
  name: z5py
  version: {{ version }}

source:
  url: https://github.com/constantinpape/z5/archive/{{ version }}.tar.gz
  sha256: {{ checksum }}
build:
  number: 0
  skip: true  # [py<311]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cmake
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - ninja  # [win]
    - make  # [not win]
  host:
    - python
    - numpy
    - nanobind
    - blosc
    - bzip2
    - liblzma-devel
    - zlib
    - libdeflate
    - zstd
    - nlohmann_json
    - lz4-c
  run:
    - python
    - numpy

test:
  imports:
    - z5py
  requires:
    - pip
    - zarr >=3
    - tensorstore  # [not win]
  source_files:
    - src/python/test/*.py
  commands:
    - python -c "from importlib.metadata import version; assert version('z5py') == '{{ version }}'"
    - python -m pip show z5py
    - python -m unittest discover -s src/python/test -v

about:
  home: https://github.com/constantinpape/z5
  license: MIT
  license_file: LICENSE
  summary: Lightweight C++ and Python interface for datasets in zarr and N5 format.

extra:
  recipe-maintainers:
    - constantinpape
    - SylvainCorlay
