{% set version = "2.0.18" %}
{% set checksum = "210d92a6e51bbad3226b5c6bad5b40564adb52a63638ef76687c6b90580239ba" %}

package:
  name: z5py
  version: {{ version }}

source:
  url: https://github.com/constantinpape/z5/archive/{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  number: 1
  skip: true  # [win and vc<14]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cmake
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - ninja  # [win]
    - make  # [not win]
  host:
    - python
    - numpy
    - xtensor >=0.24,<0.25
    - xtensor-python >=0.26,<0.27
    - xsimd >=8,<9
    - blosc
    - bzip2
    - xz
    - zlib
    - nlohmann_json
    # lz4 builds on conda are broken
    # - lz4-c
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - blosc
    - bzip2
    - xz
    - zlib
    # lz4 builds on conda are broken
    # - lz4-c

test:
  imports:
    - z5py
  requires:
    - zarr
  source_files:
    - src/python/test/*.py
  commands:
    - python -m unittest discover -s src/python/test -v

about:
  home: https://github.com/constantinpape/z5
  license: MIT
  license_file: LICENSE
  summary: Lightweight C++ and Python interface for datasets in zarr and N5 format.

extra:
  recipe-maintainers:
    - constantinpape
    - SylvainCorlay
