{% set version = "2.0.2" %}
{% set checksum = "dac526a37ce9cef96d519fe68c468dda518f58ff1bc72797366e1388a1b894f9" %}

package:
  name: z5py
  version: {{ version }}

source:
    url: https://github.com/constantinpape/z5/archive/{{ version }}.tar.gz
    sha256: {{ checksum }}

build:
  number: 1
  skip: True  # [win and vc<14]
  skip: True  # [py27]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - boost-cpp >=1.63
    - numpy
    - xtensor >=0.21,<0.22
    - xtensor-python >=0.24,<0.25
    - nlohmann_json
    - blosc
    - bzip2
    - xz
    - zlib

    # not sure if it's clever to build with xsimd on conda
    # for a proper build with vec instructions,
    # would need to make the build architecture specific
    # - xsimd >=7,<8
    # lz4 builds on conda are broken
    # - lz4-c
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - blosc
    - bzip2
    - xz
    - zlib
    # we build with boost filesystem on macos and so
    # we need to pin the boost version, see also
    # https://github.com/conda-forge/z5py-feedstock/issues/24
    - {{ pin_compatible('boost-cpp') }}  # [osx]
    # lz4 builds on conda are broken
    # - lz4-c

test:
  imports:
    - z5py
  source_files:
    - src/python/test/*.py
  commands:
    - python -m unittest discover -s src/python/test -v

about:
  home: https://github.com/constantinpape/z5
  license: MIT
  license_file: LICENSE
  summary: Lightweight C++ and Python interface for datasets in zarr and N5 format.

extra:
  recipe-maintainers:
    - constantinpape
    - SylvainCorlay
