{% set version = "2.0.0" %}
{% set checksum = "140ab56376c07fbfa6af610042316aaff48088b91d51fb87d7018fcb9b16e8cc" %}

package:
  name: z5py
  version: {{ version }}

source:
    url: https://github.com/constantinpape/z5/archive/{{ version }}.tar.gz
    sha256: {{ checksum }}
    patches:
        - patches/cmake_lz4_patch.file

build:
  number: 0
  # windows build is currently not working, because we need
  # msvc 15 or higher and conda-forge still uses 14, see also
  # https://github.com/conda-forge/z5py-feedstock/issues/23
  skip: True  # [win]
  skip: True  # [py27]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - boost-cpp >=1.63
    - numpy
    - xtensor >=0.19,<0.20
    - xtensor-python >=0.22,<0.23
    - xsimd >=7,<8
    - blosc
    - bzip2
    - lz4-c
    - xz
    - zlib
    - nlohmann_json
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - blosc
    - bzip2
    - lz4-c
    - xz
    - zlib
    # we build with boost filesystem on macos and so
    # we need to pin the boost version, see also
    # https://github.com/conda-forge/z5py-feedstock/issues/24
    - {{ pin_compatible('boost-cpp') }}  # [osx]

test:
  imports:
    - z5py
  source_files:
    - src/python/test/*.py
  commands:
    - python -m unittest discover -s src/python/test -v

about:
  home: https://github.com/constantinpape/z5
  license: MIT
  license_file: LICENSE
  summary: Lightweight C++ and Python interface for datasets in zarr and N5 format.

extra:
  recipe-maintainers:
    - constantinpape
    - SylvainCorlay
