{% set version = "2.0.0" %}
{% set checksum = "81d9480d3e6bec95ef710ffcc728d99ae114ed967ac40eadc880b275a715b199" %}

package:
  name: z5py
  version: {{ version }}

source:
    url: https://github.com/constantinpape/z5/archive/{{ version }}.tar.gz
    sha256: {{ checksum }}
    patches:
        - patches/cmake_lz4_patch.file

build:
  number: 0
  skip: True  # [win and vc<14]
  skip: True  # [py27]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - boost-cpp >=1.63
    - numpy
    - xtensor >=0.19,<0.20
    - xtensor-python >=0.22,<0.23
    - xsimd >=7,<8
    - blosc
    - bzip2
    - lz4-c
    - xz
    - zlib
    - nlohmann_json
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - blosc
    - bzip2
    - lz4-c
    - xz
    - zlib

test:
  imports:
    - z5py
  source_files:
    - src/python/test/*.py
  commands:
    - python -m unittest discover -s src/python/test -v

about:
  home: https://github.com/constantinpape/z5
  license: MIT
  license_file: LICENSE
  summary: Lightweight C++ and Python interface for datasets in zarr and N5 format.

extra:
  recipe-maintainers:
    - constantinpape
    - SylvainCorlay
